apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitmile-ingress
  namespace: digitmile-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - game.yourdomain.com
        - panel.yourdomain.com
      secretName: digitmile-tls
  rules:
    - host: game.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game
                port:
                  number: 80
    - host: panel.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-backend
                port:
                  number: 80