apiVersion: v1
kind: Namespace
metadata:
  name: digitmile-prod

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: digitmile-prod
type: Opaque
stringData:
  username: prod_user
  password: prod_password

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: digitmile-prod
type: Opaque
stringData:
  secret-key: prod-secret-key