# Generated by Django 6.0.1 on 2026-01-29 13:21

import digitmileapi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_school_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('region', models.CharField(default='RegionPlaceholder', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('google_maps_address', models.CharField(blank=True, default='', max_length=500)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('contact_person_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_person_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_person_phone', models.CharField(blank=True, default='', max_length=50)),
                ('director_name', models.CharField(max_length=255)),
                ('director_email', models.EmailField(blank=True, default='', max_length=254)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'municipality', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_classroom_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('classroom_key', models.CharField(max_length=100, unique=True)),
                ('classroom_name', models.CharField(default='ClassroomNamePlaceholder', max_length=255)),
                ('grade', models.IntegerField(blank=True, help_text='Grade level of the classroom', null=True)),
                ('school', models.ForeignKey(blank=True, help_text='The school where this classroom is located', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='digitmileapi.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_student_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Student date of birth', null=True)),
                ('grade', models.IntegerField(blank=True, help_text='Student grade level', null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='digitmileapi.classroom')),
            ],
            options={
                'unique_together': {('full_name', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='RunStatistics',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_run_statistics_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('player_won', models.BooleanField()),
                ('level', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('correct_moves', models.IntegerField(blank=True, null=True)),
                ('wrong_moves', models.IntegerField(blank=True, null=True)),
                ('time_elapsed', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_statistics', to='digitmileapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_run_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('player_won', models.BooleanField()),
                ('score', models.IntegerField()),
                ('elapsed_ms', models.IntegerField(help_text='Total game duration in milliseconds')),
                ('correct_moves', models.IntegerField()),
                ('wrong_moves', models.IntegerField()),
                ('map_version', models.CharField(default='1', max_length=50)),
                ('bot_version', models.CharField(default='1', max_length=50)),
                ('rng_seed', models.IntegerField(blank=True, help_text='Random seed for reproducibility', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='digitmileapi.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_teacher_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('years_teaching', models.IntegerField(blank=True, help_text='Total years of teaching experience', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='digitmileapi.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherSchoolAssignment',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_teacher_school_assignment_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('years_at_school', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='digitmileapi.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to='digitmileapi.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='schools',
            field=models.ManyToManyField(related_name='teachers', through='digitmileapi.TeacherSchoolAssignment', to='digitmileapi.school'),
        ),
        migrations.CreateModel(
            name='TurnEvent',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_turn_event_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('turn_index', models.IntegerField()),
                ('timestamp_played', models.DateTimeField()),
                ('chosen_card', models.JSONField(help_text='The card chosen by the player')),
                ('offered_cards', models.JSONField(help_text='All cards offered to the player')),
                ('was_correct', models.BooleanField()),
                ('tile_before_index', models.IntegerField(help_text='Player position before turn')),
                ('tile_before_type', models.IntegerField(help_text='Tile type at position before turn')),
                ('tile_after_index', models.IntegerField(help_text='Player position after turn')),
                ('place_before', models.IntegerField()),
                ('place_after', models.IntegerField()),
                ('card_decision_time_ms', models.IntegerField(help_text='Time taken to choose card in ms')),
                ('offered_numbers', models.JSONField(default=list, help_text='Numbers offered for selection')),
                ('chosen_number', models.IntegerField(blank=True, null=True)),
                ('number_decision_time_ms', models.IntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_events', to='digitmileapi.run')),
            ],
            options={
                'ordering': ['run', 'turn_index'],
            },
        ),
        migrations.CreateModel(
            name='SpecialTileTrigger',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_special_tile_trigger_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('chain_index', models.IntegerField(help_text='Order in the chain of special tile effects')),
                ('special_tile_index', models.IntegerField()),
                ('special_tile_type', models.IntegerField()),
                ('effect_delta_tiles', models.IntegerField(help_text='Number of tiles moved by this effect')),
                ('target_tile_index', models.IntegerField()),
                ('target_tile_type', models.IntegerField()),
                ('place_before', models.IntegerField()),
                ('place_after', models.IntegerField()),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_tile_triggers', to='digitmileapi.turnevent')),
            ],
            options={
                'ordering': ['turn', 'chain_index'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['student', 'created_at'], name='run_student_created_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['student', 'level'], name='run_student_level_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['level', 'created_at'], name='run_level_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('classroom_key', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherschoolassignment',
            unique_together={('teacher', 'school')},
        ),
        migrations.AddIndex(
            model_name='turnevent',
            index=models.Index(fields=['run', 'turn_index'], name='turn_run_index_idx'),
        ),
        migrations.AddIndex(
            model_name='turnevent',
            index=models.Index(fields=['run', 'timestamp_played'], name='turn_run_timestamp_idx'),
        ),
        migrations.AddConstraint(
            model_name='turnevent',
            constraint=models.UniqueConstraint(fields=('run', 'turn_index'), name='unique_turn_per_run'),
        ),
        migrations.AddIndex(
            model_name='specialtiletrigger',
            index=models.Index(fields=['turn', 'chain_index'], name='trigger_turn_chain_idx'),
        ),
        migrations.AddIndex(
            model_name='specialtiletrigger',
            index=models.Index(fields=['special_tile_index'], name='trigger_tile_index_idx'),
        ),
        migrations.AddIndex(
            model_name='specialtiletrigger',
            index=models.Index(fields=['special_tile_type'], name='trigger_tile_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='specialtiletrigger',
            constraint=models.UniqueConstraint(fields=('turn', 'chain_index'), name='unique_chain_per_turn'),
        ),
    ]
