# Generated by Django 6.0.1 on 2026-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='game_map',
            field=models.JSONField(default=list, help_text='The game map tiles for this run (list of TileSnapshot objects)'),
        ),
        migrations.AddField(
            model_name='run',
            name='place',
            field=models.IntegerField(default=4, help_text='Final place (1st, 2nd, 3rd, 4th)'),
        ),
    ]
