# Generated by Django 6.0.1 on 2026-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0002_run_game_map_run_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnevent',
            name='bot_positions_after',
            field=models.JSONField(default=list, help_text='Bot positions after turn resolution (list of {tileMapIndex, botID})'),
        ),
        migrations.AddField(
            model_name='turnevent',
            name='bot_positions_before',
            field=models.JSONField(default=list, help_text='Bot positions before player move (list of {tileMapIndex, botID})'),
        ),
    ]
