# Generated by Django 6.0.1 on 2026-02-15 18:05

import re

from django.db import migrations, models


CARD_FAMILY_BY_TYPE = {
    "MoveX": "move",
    "IfXMoveYElseMoveZ": "conditional_tile",
    "IfBagEqualXMoveYElseMoveZ": "conditional_bag_eq",
    "IfBagLessXMoveYElseMoveZ": "conditional_bag_lt",
    "IfBagGreaterXMoveYElseMoveZ": "conditional_bag_gt",
    "BagCount": "bagcount",
    "ForXMoveY": "foreach_tile",
    "Back": "back",
}


def normalize_card_type(card_type):
    if card_type in {"Bug", "Back"}:
        return "Back"
    if isinstance(card_type, str) and card_type.startswith("AllBack"):
        return "Back"
    return card_type if isinstance(card_type, str) and card_type else "unknown"


def parse_tile_type(card_data):
    if not card_data:
        return None

    raw = str(card_data).strip()
    if raw.startswith("[") and raw.endswith("]"):
        raw = raw[1:-1].strip()
    if raw.lower().startswith("carddata:"):
        raw = raw.split(":", 1)[1].strip()

    match = re.search(r"tileType\s*=\s*([^,]*)", raw)
    if not match:
        return None

    raw_value = match.group(1).strip()
    if raw_value == "":
        return None

    try:
        return int(raw_value)
    except (TypeError, ValueError):
        return None


def populate_turn_event_card_metadata(apps, schema_editor):
    TurnEvent = apps.get_model("digitmileapi", "TurnEvent")
    update_batch = []

    for turn in TurnEvent.objects.all().only("id", "chosen_card").iterator(chunk_size=2000):
        chosen_card = turn.chosen_card if isinstance(turn.chosen_card, dict) else {}
        card_type = normalize_card_type(chosen_card.get("type"))
        turn.chosen_card_type = card_type
        turn.chosen_card_family = CARD_FAMILY_BY_TYPE.get(card_type, "unknown")
        turn.chosen_card_tile_type = parse_tile_type(chosen_card.get("data"))
        update_batch.append(turn)

        if len(update_batch) >= 1000:
            TurnEvent.objects.bulk_update(
                update_batch,
                ["chosen_card_type", "chosen_card_family", "chosen_card_tile_type"],
                batch_size=1000,
            )
            update_batch = []

    if update_batch:
        TurnEvent.objects.bulk_update(
            update_batch,
            ["chosen_card_type", "chosen_card_family", "chosen_card_tile_type"],
            batch_size=1000,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("digitmileapi", "0003_turnevent_bot_positions_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnevent",
            name="chosen_card_family",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="Card family derived from chosen card type",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="turnevent",
            name="chosen_card_tile_type",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Parsed tileType from chosen card data when available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turnevent",
            name="chosen_card_type",
            field=models.CharField(
                db_index=True,
                default="unknown",
                help_text="Normalized chosen card type for analytics filtering",
                max_length=64,
            ),
        ),
        migrations.RunPython(
            populate_turn_event_card_metadata,
            reverse_code=noop_reverse,
        ),
    ]
