# Generated by Django 6.0.1 on 2026-03-12 18:40

import digitmileapi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0005_weeklycompactionrun_run_raw_data_compacted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWeekCardTypeStats',
            fields=[
                ('week_start', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=digitmileapi.models.generate_student_week_card_type_stats_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('card_type', models.CharField(max_length=64)),
                ('chosen_count', models.PositiveIntegerField(default=0)),
                ('decision_time_sum_ms', models.BigIntegerField(default=0)),
                ('decision_time_count', models.PositiveIntegerField(default=0)),
                ('decision_time_sum_sq_ms', models.BigIntegerField(default=0)),
                ('decision_time_min_ms', models.IntegerField(blank=True, null=True)),
                ('decision_time_max_ms', models.IntegerField(blank=True, null=True)),
                ('clipped_decision_time_sum_ms', models.BigIntegerField(default=0)),
                ('clipped_decision_time_sum_sq_ms', models.BigIntegerField(default=0)),
                ('outlier_count', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.teacher')),
            ],
            options={
                'ordering': ['student', 'week_start', 'level', 'card_type'],
                'indexes': [models.Index(fields=['teacher', 'week_start', 'level', 'card_type'], name='sct_tchr_wk_lvl_type_idx'), models.Index(fields=['classroom', 'week_start', 'level'], name='sct_clsrm_wk_lvl_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'week_start', 'level', 'card_type'), name='unique_student_week_card_type_stats')],
            },
        ),
    ]
