# Generated by Django 6.0.1 on 2026-03-12 19:41

import digitmileapi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0006_studentweekcardtypestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRunBucketTrend',
            fields=[
                ('id', models.CharField(default=digitmileapi.models.generate_student_run_bucket_trend_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('bucket_index', models.PositiveIntegerField()),
                ('bucket_size_runs', models.PositiveIntegerField(default=5)),
                ('first_run_created_at', models.DateTimeField()),
                ('last_run_created_at', models.DateTimeField()),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('correct_moves', models.PositiveIntegerField(default=0)),
                ('wrong_moves', models.PositiveIntegerField(default=0)),
                ('score_sum', models.BigIntegerField(default=0)),
                ('score_count', models.PositiveIntegerField(default=0)),
                ('score_sum_sq', models.BigIntegerField(default=0)),
                ('elapsed_sum_ms', models.BigIntegerField(default=0)),
                ('elapsed_count', models.PositiveIntegerField(default=0)),
                ('elapsed_sum_sq', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitmileapi.teacher')),
            ],
            options={
                'ordering': ['student', 'level', 'bucket_index'],
                'indexes': [models.Index(fields=['teacher', 'level', 'bucket_index'], name='srb_tchr_lvl_bucket_idx'), models.Index(fields=['classroom', 'level', 'bucket_index'], name='srb_clsrm_lvl_bucket_idx'), models.Index(fields=['student', 'level', 'first_run_created_at'], name='srb_student_level_first_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'level', 'bucket_index'), name='unique_student_run_bucket_trend')],
            },
        ),
    ]
