# Generated by Django 6.0 on 2025-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0010_classroom_grade_student_date_of_birth_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='director_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_email',
            field=models.EmailField(max_length=254),
        ),
    ]
