# Generated by Django 6.0.1 on 2026-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0011_alter_school_address_alter_school_director_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='runstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
