# Generated by Django 6.0.1 on 2026-01-20 20:25

from django.db import migrations
from django.utils import timezone


def backfill_runstatistics_timestamps(apps, schema_editor):
    run_statistics = apps.get_model('digitmileapi', 'RunStatistics')
    now = timezone.now()
    run_statistics.objects.filter(created_at__isnull=True).update(created_at=now)
    run_statistics.objects.filter(updated_at__isnull=True).update(updated_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('digitmileapi', '0012_runstatistics_created_at_runstatistics_updated_at'),
    ]

    operations = [
        migrations.RunPython(backfill_runstatistics_timestamps, migrations.RunPython.noop),
    ]
