"""
Django settings for digitmile project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.conf.global_settings import APPEND_SLASH
from dotenv import load_dotenv

# Load .env file from the 'digitmile' directory, which is the parent of the current directory
load_dotenv(dotenv_path=Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CORS_ALLOW_ALL_ORIGINS = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# FORCE_SCRIPT_NAME = '/panel'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-)bpw(3%nq@n54q!qfc=stwjs8^-2nar(%=s*@-f9dbm4__0h@s",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

SERVER_IP = os.getenv("SERVER_IP")
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "digit.mile.mk,localhost,127.0.0.1").split(
    ","
)
if SERVER_IP:
    ALLOWED_HOSTS.append(SERVER_IP)

CSRF_TRUSTED_ORIGINS = [
    "https://digit.mile.mk",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ALLOWED_HOSTS += [
#     '10.1.0.*',
#     'django-backend',
#     'django-backend.digitmile-dev.svc.cluster.local',
# ]

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    "digitmileapi",  # Must be before django.contrib.admin to override admin templates
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "captcha",
]

MIDDLEWARE = [
    "digitmileapi.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Add this for language switching
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "digitmile.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",  # Add this for translations
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "digitmile.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# print(os.getenv('DB_NAME'))
# print(os.getenv('DB_USER'))
# print(os.getenv('DB_PASS'))
# print(os.getenv('DB_HOST'))
# print(os.getenv('DB_PORT'))
# PASTE THIS ENTIRE BLOCK:
db_port_env = os.getenv("DB_PORT")
processed_db_port = (
    ""  # Default to empty string, telling Django not to specify a port to psycopg2
)

if db_port_env and db_port_env.strip().isdigit():
    # If DB_PORT is set and is a number, use it as an integer
    processed_db_port = int(db_port_env.strip())
elif not db_port_env:
    # If DB_PORT is not set in .env at all, default to 5432 (integer)
    processed_db_port = 5432
# If DB_PORT is set but is not a simple number (e.g., an empty string from .env, or non-numeric),
# processed_db_port remains '', which is fine for Django's database wrapper.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": processed_db_port,  # Use the explicitly processed port
        # PgBouncer transaction pooling requires these two settings:
        # - CONN_MAX_AGE=0: Django must not hold persistent connections;
        #   PgBouncer owns the pool, not Django.
        # - DISABLE_SERVER_SIDE_CURSORS=True: PgBouncer can't forward prepared
        #   statements across transaction boundaries.
        "CONN_MAX_AGE": 0,
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }
}
# END OF BLOCK TO PASTE

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Supported languages
LANGUAGES = [
    ("en", "English"),
    ("mk", "Македонски"),  # Macedonian
    ("sq", "Shqip"),  # Albanian
    # Add more languages as needed
]

# Path where translation files will be stored
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files with WhiteNoise
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/panel/"
LOGIN_REDIRECT_URL = "/panel/"
LOGOUT_REDIRECT_URL = "/panel/"

# Email configuration
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@digitmile.com")
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

REPLAY_ARCHIVE_ROOT = Path(
    os.getenv("REPLAY_ARCHIVE_ROOT", BASE_DIR / "replay_archives")
)
REPLAY_ARCHIVE_COMPRESSION_LEVEL = int(
    os.getenv("REPLAY_ARCHIVE_COMPRESSION_LEVEL", "6")
)
REPLAY_ARCHIVE_HOT_RETENTION_DAYS = int(
    os.getenv("REPLAY_ARCHIVE_HOT_RETENTION_DAYS", "7")
)
BENCHMARK_TIME_OVERRIDE_ENABLED = (
    os.getenv("BENCHMARK_TIME_OVERRIDE_ENABLED", "False") == "True"
)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # Log to console (stdout) instead of files
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Add any custom loggers you had pointing to 'file' handler
        "email": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
