apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql/statefulset.yaml
  - postgresql/service.yaml
  - django/deployment.yaml
  - django/service.yaml
  - django/configmap.yaml
  - game/deployment.yaml
  - game/service.yaml