apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: digitmile
type: Opaque
stringData:
  username: digitmile_user
  password: CHANGE_ME_TO_REAL_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: digitmile
type: Opaque
stringData:
  secret-key: CHANGE_ME_TO_RANDOM_STRING
  superuser-username: damjanadmin
  superuser-password: "123"
  superuser-email: damjan.avramovski@gmail.com
  email_host_password : "vstmfndeoasebrss"
  google_maps_api_key : "AIzaSyD8M4oWzr2MC6PEsaOQQb8rA6RtpAQhDKs"